version: '3.8'

services:
  django:
    build: ./ChopDeck
    container_name: chopdeck_django
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - RASA_API_URL=http://rasa:5005
  
  rasa:
    build: ./rasa_bot
    container_name: chopdeck_rasa
    ports:
      - "5005:5005"
      - "5055:5055"
    command: sh -c "rasa run actions --port 5055 & rasa run --enable-api --cors '*' --port 5005 & wait"