# Generated by Django 5.2.6 on 2025-09-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChopDeckApp', '0003_rename_name_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='stars',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
