# Generated by Django 5.2.6 on 2025-09-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChopDeckApp', '0007_remove_comment_blog_comment_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total',
        ),
    ]
