# Generated by Django 5.2.6 on 2025-09-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChopDeckApp', '0008_rename_total_amount_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
