# Generated by Django 5.2.6 on 2025-09-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChopDeckApp', '0002_category_blog_author_blog_content_blog_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
