# Generated by Django 5.2.6 on 2025-09-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChopDeckApp', '0005_alter_blog_image_alter_fooditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
